
/* This code was auto-generated by editor */



#include "../main.h"

extern kineticArtLevel Menu;
extern kineticArtLevel Level02;
#define PREV_LEVEL &Menu
#define NEXT_LEVEL &Level02


static void init(void)
{
	makeSpaces();
	staticBodyInit();
	makeWalls();

	createPlayer();
	emitterNew(-1, 2, (BITMAP *)data[rc_p_mid_y].dat, Player, underspace);
	emitterNew(-1, 3, (BITMAP *)data[rc_p_big_g].dat, Player, underspace);
	emitterNew(-1, 1, (BITMAP *)data[rc_p_big_y].dat, Bite, underspace);

	createCommonHandlers();

{  /* Total bodies: 42, total joints: 73 */
	int health = 1;
	cpBody *body0 = staticBody;
	cpBody *body1 = createPolyUniWrapper(106, 1, 1.0, 75.803873, cpv(399.0, 333.172223), cpv(0.0, 32.666668), cpvzero, -1.678188, 0.0, 0.0, 0.9, 0.5, OBJECT_CT, OBJECT_LAYER, health);
	cpBody *body2 = createPolyUniWrapper(106, 2, 1.0, 75.803873, cpv(427.0, 292.0), cpvzero, cpvzero, 2.672327, 0.0, 0.0, 0.9, 0.5, OBJECT_CT, OBJECT_LAYER, health);
	cpBody *body3 = createPolyUniWrapper(106, 3, 1.0, 75.803873, cpv(365.0, 267.0), cpvzero, cpvzero, 0.427948, 0.0, 0.0, 0.9, 0.5, OBJECT_CT, OBJECT_LAYER, health);
	cpBody *body4 = createPolyUniWrapper(106, 4, 1.0, 75.803873, cpv(462.0, 281.0), cpvzero, cpvzero, 2.819842, 0.0, 0.0, 0.9, 0.5, OBJECT_CT, OBJECT_LAYER, health);
	cpBody *body5 = createPolyUniWrapper(106, 5, 1.0, 75.803873, cpv(369.0, 192.0), cpvzero, cpvzero, -1.948765, 0.0, 0.0, 0.9, 0.5, OBJECT_CT, OBJECT_LAYER, health);
	cpBody *body6 = createPolyUniWrapper(106, 6, 1.0, 75.803873, cpv(413.0, 207.0), cpvzero, cpvzero, 2.265535, 0.0, 0.0, 0.9, 0.5, OBJECT_CT, OBJECT_LAYER, health);
	cpBody *body7 = createPolyUniWrapper(106, 7, 1.0, 75.803873, cpv(391.0, 260.0), cpvzero, cpvzero, -1.775673, 0.0, 0.0, 0.9, 0.5, OBJECT_CT, OBJECT_LAYER, health);
	cpBody *body8 = createPolyUniWrapper(106, 8, 1.0, 75.803873, cpv(396.0, 295.0), cpvzero, cpvzero, -1.728565, 0.0, 0.0, 0.9, 0.5, OBJECT_CT, OBJECT_LAYER, health);
	cpBody *body9 = createPolyUniWrapper(106, 9, 1.0, 75.803873, cpv(430.0, 401.0), cpvzero, cpvzero, -2.471071, 0.0, 0.0, 0.9, 0.5, OBJECT_CT, OBJECT_LAYER, health);
	cpBody *body10 = createPolyUniWrapper(106, 10, 1.0, 75.803873, cpv(407.0, 369.0), cpvzero, cpvzero, -2.153149, 0.0, 0.0, 0.9, 0.5, OBJECT_CT, OBJECT_LAYER, health);
	cpBody *body43 = createPolyUniWrapper(107, 43, 1.0, 75.803873, cpv(266.0, 92.0), cpvzero, cpvzero, 0.310998, 0.0, 0.0, 0.9, 0.5, OBJECT_CT, OBJECT_LAYER, health);
	cpBody *body12 = createPolyUniWrapper(109, 12, 1.0, 75.803873, cpv(382.0, 225.0), cpvzero, cpvzero, -1.898535, 0.0, 0.0, 0.9, 0.5, OBJECT_CT, OBJECT_LAYER, health);
	cpBody *body13 = createPolyUniWrapper(109, 13, 1.0, 75.803873, cpv(357.0, 159.0), cpvzero, cpvzero, -1.904041, 0.0, 0.0, 0.9, 0.5, OBJECT_CT, OBJECT_LAYER, health);
	cpBody *body14 = createPolyUniWrapper(109, 14, 1.0, 75.803873, cpv(440.0, 184.0), cpvzero, cpvzero, 2.521343, 0.0, 0.0, 0.9, 0.5, OBJECT_CT, OBJECT_LAYER, health);
	cpBody *body15 = createPolyUniWrapper(109, 15, 1.0, 75.803873, cpv(400.0, 121.0), cpvzero, cpvzero, -3.038511, 0.0, 0.0, 0.9, 0.5, OBJECT_CT, OBJECT_LAYER, health);
	cpBody *body16 = createPolyUniWrapper(109, 16, 1.0, 75.803873, cpv(277.0, 123.0), cpvzero, cpvzero, -0.197396, 0.0, 0.0, 0.9, 0.5, OBJECT_CT, OBJECT_LAYER, health);
	cpBody *body17 = createPolyUniWrapper(109, 17, 1.0, 75.803873, cpv(304.0, 163.0), cpvzero, cpvzero, -0.942960, 0.0, 0.0, 0.9, 0.5, OBJECT_CT, OBJECT_LAYER, health);
	cpBody *body18 = createPolyUniWrapper(109, 18, 1.0, 75.803873, cpv(295.0, 73.0), cpvzero, cpvzero, 0.835357, 0.0, 0.0, 0.9, 0.5, OBJECT_CT, OBJECT_LAYER, health);
	cpBody *body19 = createPolyUniWrapper(109, 19, 1.0, 75.803873, cpv(330.0, 260.0), cpvzero, cpvzero, -0.083141, 0.0, 0.0, 0.9, 0.5, OBJECT_CT, OBJECT_LAYER, health);
	cpBody *body20 = createPolyUniWrapper(109, 20, 1.0, 75.803873, cpv(385.0, 73.0), cpvzero, cpvzero, 2.417343, 0.0, 0.0, 0.9, 0.5, OBJECT_CT, OBJECT_LAYER, health);
	cpBody *body21 = createPolyUniWrapper(107, 21, 1.0, 75.803873, cpv(517.0, 275.0), cpvzero, cpvzero, -2.972491, 0.0, 0.0, 0.9, 0.5, OBJECT_CT, OBJECT_LAYER, health);
	cpBody *body22 = createPolyUniWrapper(107, 22, 1.0, 75.803873, cpv(271.0, 262.0), cpvzero, cpvzero, -0.218669, 0.0, 0.0, 0.9, 0.5, OBJECT_CT, OBJECT_LAYER, health);
	cpBody *body23 = createPolyUniWrapper(107, 23, 1.0, 75.803873, cpv(311.0, 43.0), cpvzero, cpvzero, 1.249046, 0.0, 0.0, 0.9, 0.5, OBJECT_CT, OBJECT_LAYER, health);
	cpBody *body24 = createPolyUniWrapper(107, 24, 1.0, 75.803873, cpv(408.0, 92.0), cpvzero, cpvzero, 2.867425, 0.0, 0.0, 0.9, 0.5, OBJECT_CT, OBJECT_LAYER, health);
	cpBody *body25 = createPolyUniWrapper(107, 25, 1.0, 75.803873, cpv(475.0, 174.0), cpvzero, cpvzero, -2.873976, 0.0, 0.0, 0.9, 0.5, OBJECT_CT, OBJECT_LAYER, health);
	cpBody *body26 = createPolyUniWrapper(107, 26, 1.0, 75.803873, cpv(458.0, 150.0), cpvzero, cpvzero, 1.532354, 0.0, 0.0, 0.9, 0.5, OBJECT_CT, OBJECT_LAYER, health);
	cpBody *body27 = createPolyUniWrapper(105, 27, 1.0, 75.803873, cpv(490.0, 260.0), cpvzero, cpvzero, 2.144463, 0.0, 0.0, 0.9, 0.5, OBJECT_CT, OBJECT_LAYER, health);
	cpBody *body28 = createPolyUniWrapper(105, 28, 1.0, 75.803873, cpv(496.0, 290.0), cpvzero, cpvzero, -2.516957, 0.0, 0.0, 0.9, 0.5, OBJECT_CT, OBJECT_LAYER, health);
	cpBody *body29 = createPolyUniWrapper(105, 29, 1.0, 75.803873, cpv(306.0, 133.0), cpvzero, cpvzero, -0.560360, 0.0, 0.0, 0.9, 0.5, OBJECT_CT, OBJECT_LAYER, health);
	cpBody *body30 = createPolyUniWrapper(105, 30, 0.100000, 75.803873, cpv(373.0, 103.0), cpvzero, cpvzero, 2.844528, 0.0, 0.0, 0.9, 0.5, OBJECT_CT, OBJECT_LAYER, health);
	cpBody *body31 = createPolyUniWrapper(105, 31, 0.100000, 75.803873, cpv(370.0, 133.0), cpvzero, cpvzero, -2.634494, 0.0, 0.0, 0.9, 0.5, OBJECT_CT, OBJECT_LAYER, health);
	cpBody *body32 = createPolyUniWrapper(108, 32, 1.0, 75.803873, cpv(340.0, 115.0), cpvzero, cpvzero, 1.121037, 90.0, 0.0, 0.9, 0.5, OBJECT_CT, OBJECT_LAYER, health);
	cpBody *body33 = createPolyUniWrapper(105, 33, 1.0, 75.803873, cpv(302.0, 103.0), cpvzero, cpvzero, 0.428778, 0.0, 0.0, 0.9, 0.5, OBJECT_CT, OBJECT_LAYER, health);
	cpBody *body34 = createPolyUniWrapper(105, 34, 1.0, 75.803873, cpv(323.0, 78.0), cpvzero, cpvzero, 1.262744, 0.0, 0.0, 0.9, 0.5, OBJECT_CT, OBJECT_LAYER, health);
	cpBody *body35 = createPolyUniWrapper(105, 35, 0.100000, 75.803873, cpv(355.0, 78.0), cpvzero, cpvzero, 1.923787, 0.0, 0.0, 0.9, 0.5, OBJECT_CT, OBJECT_LAYER, health);
	cpBody *body36 = createPolyUniWrapper(105, 36, 1.0, 75.803873, cpv(296.0, 246.0), cpvzero, cpvzero, 0.386876, 0.0, 0.0, 0.9, 0.5, OBJECT_CT, OBJECT_LAYER, health);
	cpBody *body37 = createPolyUniWrapper(105, 37, 1.0, 75.803873, cpv(297.0, 276.0), cpvzero, cpvzero, -0.694738, 0.0, 0.0, 0.9, 0.5, OBJECT_CT, OBJECT_LAYER, health);
	cpBody *body38 = createPolyUniWrapper(105, 38, 1.0, 75.803873, cpv(484.0, 148.0), cpvzero, cpvzero, 2.498092, 0.0, 0.0, 0.9, 0.5, OBJECT_CT, OBJECT_LAYER, health);
	cpBody *body39 = createPolyUniWrapper(105, 39, 1.0, 75.803873, cpv(331.0, 150.0), cpvzero, cpvzero, -1.354711, 0.0, 0.0, 0.9, 0.5, OBJECT_CT, OBJECT_LAYER, health);
	cpBody *body40 = createPolyUniWrapper(109, 40, 1.0, 75.803873, cpv(341.0, 53.0), cpvzero, cpvzero, 1.570796, 0.0, 0.0, 0.9, 0.5, OBJECT_CT, OBJECT_LAYER, health);
	cpBody *body41 = createPolyUniWrapper(107, 41, 1.0, 75.803873, cpv(275.0, 153.0), cpvzero, cpvzero, -0.471778, 0.0, 0.0, 0.9, 0.5, OBJECT_CT, OBJECT_LAYER, health);
	cpBody *body44 = createPolyUniWrapper(107, 44, 1.0, 75.803873, cpv(372.0, 47.0), cpvzero, cpvzero, 2.144237, 0.0, 0.0, 0.9, 0.5, OBJECT_CT, OBJECT_LAYER, health);
	cpSpaceAddConstraint(space, cpPinJointNew(body9, body10, cpv(12.184740, -0.729463), cpv(-11.651652, -0.488881)));
	cpSpaceAddConstraint(space, cpPinJointNew(body10, body1, cpv(10.531301, -1.446271), cpv(-10.658215, -2.154813)));
	cpSpaceAddConstraint(space, cpPinJointNew(body1, body8, cpv(11.215046, 0.203254), cpv(-10.032918, -0.583570)));
	cpSpaceAddConstraint(space, cpPinJointNew(body8, body7, cpv(12.008079, 0.897800), cpv(-9.994307, -1.055378)));
	cpSpaceAddConstraint(space, cpPinJointNew(body7, body12, cpv(13.135012, 0.686632), cpv(-10.433436, -0.378709)));
	cpSpaceAddConstraint(space, cpPinJointNew(body12, body5, cpv(13.917559, -0.549128), cpv(-11.699711, -0.341697)));
	cpSpaceAddConstraint(space, cpPinJointNew(body5, body13, cpv(12.998160, -0.218686), cpv(-10.758303, 0.508839)));
	cpSpaceAddConstraint(space, cpPinJointNew(body32, body13, cpv(13.880917, 1.148980), cpv(14.865358, -0.145382)));
	cpSpaceAddConstraint(space, cpPinJointNew(body12, body6, cpv(-7.309086, 5.964668), cpv(12.675651, 1.152332)));
	cpSpaceAddConstraint(space, cpPinJointNew(body6, body14, cpv(-12.803688, 0.256074), cpv(13.019736, 0.697486)));
	cpSpaceAddConstraint(space, cpPinJointNew(body8, body3, cpv(8.371988, -1.705821), cpv(12.992854, -0.430967)));
	cpSpaceAddConstraint(space, cpPinJointNew(body3, body19, cpv(-13.407860, -0.478852), cpv(13.038140, 0.083045)));
	cpSpaceAddConstraint(space, cpPinJointNew(body8, body2, cpv(-7.182402, 6.957952), cpv(13.855865, 1.419504)));
	cpSpaceAddConstraint(space, cpPinJointNew(body2, body4, cpv(-13.416196, -0.075372), cpv(12.332883, 0.948683)));
	cpSpaceAddConstraint(space, cpPivotJointNew2(body14, body0, cpv(0.0, -0.0), cpv(440.0, 184.0)));
	cpSpaceAddConstraint(space, cpPivotJointNew2(body4, body0, cpv(4.743416, 1.581139), cpv(457.0, 281.0)));
	cpSpaceAddConstraint(space, cpPivotJointNew2(body19, body0, cpv(2.076137, -0.830455), cpv(332.0, 259.0)));
	cpSpaceAddConstraint(space, cpPivotJointNew2(body32, body0, cpv(-7.173360, -1.242140), cpv(338.0, 108.0)));
	cpSpaceAddConstraint(space, cpPivotJointNew2(body9, body0, cpv(-5.808690, 7.159548), cpv(439.0, 399.0)));
	cpSpaceAddConstraint(space, cpPivotJointNew2(body31, body0, cpv(-0.0, 0.0), cpv(370.0, 133.0)));
	cpSpaceAddConstraint(space, cpPivotJointNew2(body30, body0, cpv(0.0, -0.0), cpv(373.0, 103.0)));
	cpSpaceAddConstraint(space, cpPivotJointNew2(body35, body0, cpv(0.0, -0.0), cpv(355.0, 78.0)));
	cpSpaceAddConstraint(space, cpPivotJointNew2(body34, body0, cpvzero, cpv(323.0, 78.0)));
	cpSpaceAddConstraint(space, cpPivotJointNew2(body33, body0, cpvzero, cpv(302.0, 103.0)));
	cpSpaceAddConstraint(space, cpPivotJointNew2(body29, body0, cpvzero, cpv(306.0, 133.0)));
	cpSpaceAddConstraint(space, cpPivotJointNew2(body39, body0, cpvzero, cpv(331.0, 150.0)));
	cpSpaceAddConstraint(space, cpPivotJointNew2(body17, body0, cpvzero, cpv(304.0, 163.0)));
	cpSpaceAddConstraint(space, cpPivotJointNew2(body16, body0, cpvzero, cpv(277.0, 123.0)));
	cpSpaceAddConstraint(space, cpPivotJointNew2(body18, body0, cpvzero, cpv(295.0, 73.0)));
	cpSpaceAddConstraint(space, cpPivotJointNew2(body40, body0, cpvzero, cpv(341.0, 53.0)));
	cpSpaceAddConstraint(space, cpPivotJointNew2(body20, body0, cpv(0.0, -0.0), cpv(385.0, 73.0)));
	cpSpaceAddConstraint(space, cpPivotJointNew2(body15, body0, cpv(-0.0, 0.0), cpv(400.0, 121.0)));
	cpSpaceAddConstraint(space, cpPivotJointNew2(body24, body0, cpv(0.0, -0.0), cpv(408.0, 92.0)));
	cpSpaceAddConstraint(space, cpPivotJointNew2(body44, body0, cpv(0.0, -0.0), cpv(372.0, 47.0)));
	cpSpaceAddConstraint(space, cpPivotJointNew2(body23, body0, cpvzero, cpv(311.0, 43.0)));
	cpSpaceAddConstraint(space, cpPivotJointNew2(body43, body0, cpvzero, cpv(266.0, 92.0)));
	cpSpaceAddConstraint(space, cpPivotJointNew2(body41, body0, cpvzero, cpv(275.0, 153.0)));
	cpSpaceAddConstraint(space, cpDampedSpringNew(body32, body30, cpv(-2.329013, -6.676504), cpv(12.352542, 0.643971), 16.492423, 10.0, 0.0));
	cpSpaceAddConstraint(space, cpDampedSpringNew(body32, body35, cpv(-9.502372, -7.918644), cpv(13.334350, 1.481594), 14.317821, 10.0, 0.0));
	cpSpaceAddConstraint(space, cpDampedSpringNew(body32, body34, cpv(-15.185164, 1.552675), cpv(10.438869, 0.173259), 15.231546, 10.0, 0.0));
	cpSpaceAddConstraint(space, cpDampedSpringNew(body32, body33, cpv(-10.620299, 8.198125), cpv(12.576733, -1.351219), 14.142136, 10.0, 0.0));
	cpSpaceAddConstraint(space, cpDampedSpringNew(body29, body32, cpv(11.659585, 0.232527), cpv(-2.111638, 8.974463), 18.027756, 10.0, 0.0));
	cpSpaceAddConstraint(space, cpDampedSpringNew(body39, body32, cpv(14.103235, -1.048213), cpv(4.564865, 6.645450), 14.317821, 10.0, 0.0));
	cpSpaceAddConstraint(space, cpDampedSpringNew(body32, body31, cpv(6.676504, -2.329013), cpv(14.375031, 1.165543), 13.928388, 10.0, 0.0));
	cpSpaceAddConstraint(space, cpDampedSpringNew(body32, body20, cpv(-6.365968, -7.514948), cpv(12.127983, 1.382763), 40.459857, 10.0, 0.0));
	cpSpaceAddConstraint(space, cpDampedSpringNew(body32, body15, cpv(2.142692, -6.738611), cpv(14.131483, 0.548795), 39.319207, 10.0, 0.0));
	cpSpaceAddConstraint(space, cpDampedSpringNew(body32, body17, cpv(1.459515, 8.477607), cpv(13.601464, 0.013053), 38.275318, 10.0, 0.0));
	cpSpaceAddConstraint(space, cpDampedSpringNew(body32, body16, cpv(-5.682791, 9.471319), cpv(13.335897, -0.392232), 39.458839, 10.0, 0.0));
	cpSpaceAddConstraint(space, cpDampedSpringNew(body32, body18, cpv(-13.353007, 4.658026), cpv(12.041129, 0.105934), 35.468296, 10.0, 0.0));
	cpSpaceAddConstraint(space, cpDampedSpringNew(body32, body40, cpv(-13.477221, -4.285384), cpv(13.0, -1.0), 35.227830, 10.0, 0.0));
	cpSpaceAddConstraint(space, cpPivotJointNew2(body38, body0, cpv(0.0, -0.0), cpv(484.0, 148.0)));
	cpSpaceAddConstraint(space, cpPivotJointNew2(body25, body0, cpv(-0.0, 0.0), cpv(475.0, 174.0)));
	cpSpaceAddConstraint(space, cpPivotJointNew2(body26, body0, cpvzero, cpv(458.0, 150.0)));
	cpSpaceAddConstraint(space, cpPivotJointNew2(body21, body0, cpv(-0.0, 0.0), cpv(517.0, 275.0)));
	cpSpaceAddConstraint(space, cpPivotJointNew2(body27, body0, cpv(0.0, -0.0), cpv(490.0, 260.0)));
	cpSpaceAddConstraint(space, cpPivotJointNew2(body28, body0, cpv(-0.0, 0.0), cpv(496.0, 290.0)));
	cpSpaceAddConstraint(space, cpPivotJointNew2(body36, body0, cpvzero, cpv(296.0, 246.0)));
	cpSpaceAddConstraint(space, cpPivotJointNew2(body37, body0, cpvzero, cpv(297.0, 276.0)));
	cpSpaceAddConstraint(space, cpPivotJointNew2(body22, body0, cpvzero, cpv(271.0, 262.0)));
	cpSpaceAddConstraint(space, cpPinJointNew(body27, body4, cpv(12.740890, 1.292179), cpv(-12.016655, 1.264911)));
	cpSpaceAddConstraint(space, cpPinJointNew(body21, body4, cpv(14.305199, 0.601059), cpv(-10.119289, 1.897367)));
	cpSpaceAddConstraint(space, cpPinJointNew(body28, body4, cpv(12.790176, 0.641395), cpv(-11.700427, 0.316228)));
	cpSpaceAddConstraint(space, cpPinJointNew(body26, body14, cpv(11.952701, 1.460459), cpv(-9.764802, 1.627467)));
	cpSpaceAddConstraint(space, cpPinJointNew(body38, body14, cpv(12.200000, 0.400000), cpv(-14.182212, 0.929981)));
	cpSpaceAddConstraint(space, cpPinJointNew(body25, body14, cpv(12.630581, 0.684416), cpv(-13.833469, -1.278724)));
	cpSpaceAddConstraint(space, cpPinJointNew(body36, body19, cpv(12.999593, 0.102899), cpv(-11.626367, -4.982729)));
	cpSpaceAddConstraint(space, cpPinJointNew(body22, body19, cpv(13.341223, -0.108465), cpv(-11.958549, -0.996546)));
	cpSpaceAddConstraint(space, cpPinJointNew(body37, body19, cpv(12.803688, 0.256074), cpv(-13.287277, 2.906592)));
	cpSpaceAddConstraint(space, cpDampedSpringNew(body24, body32, cpv(13.055953, 1.594391), cpv(-3.695367, -8.446553), 50.960769, 10.0, 0.0));
	cpSpaceAddConstraint(space, cpDampedSpringNew(body44, body32, cpv(13.038111, -0.087504), cpv(-9.471319, -5.682791), 51.884487, 10.0, 0.0));
	cpSpaceAddConstraint(space, cpDampedSpringNew(body23, body32, cpv(13.597794, 0.316228), cpv(-13.849863, 1.086873), 50.328918, 10.0, 0.0));
	cpSpaceAddConstraint(space, cpDampedSpringNew(body43, body32, cpv(12.648379, 0.136004), cpv(-11.551904, 5.527524), 53.150729, 10.0, 0.0));
	cpSpaceAddConstraint(space, cpDampedSpringNew(body41, body32, cpv(12.070732, 0.545364), cpv(-3.446939, 9.440265), 54.405882, 10.0, 0.0));
}

}

static void destroy(void)
{
	removeCommonHandlers();
	freeSpaces();
}

static void update(void)
{
	finishHelper();
	if (space->bodies->num == 3 && partspace->bodies->num == 0) runLevel(NEXT_LEVEL);
	if (key[KEY_ESC]) escPause();

	#ifndef RELEASE
	if (key[KEY_F11]) runLevel(PREV_LEVEL);
	if (key[KEY_F12]) runLevel(NEXT_LEVEL);
	#endif
}

static void draw(void)
{
	BGBLIT(rc_bg14)
}


const kineticArtLevel Level01 = {
	1,
	"The start",
	"Music/game.ogg",
	init,
	update,
	draw,
	noMouse,
	destroy,
};

