/* Allegro datafile object indexes, produced by grabber v4.2.0, MinGW32 */
/* Datafile: c:\Code\A\project\data.dat */
/* Date: Sun Oct 31 02:26:26 2010 */
/* Do not hand edit! */

#define rc_-------(objects)              0        /*      */
#define rc_ball                          1        /* BMP  */
#define rc_ball_life                     2        /* BMP  */
#define rc_bite                          3        /* BMP  */
#define rc_gem01r                        4        /* BMP  */
#define rc_gem01g                        5        /* BMP  */
#define rc_gem01b                        6        /* BMP  */
#define rc_gem01y                        7        /* BMP  */
#define rc_gem01v                        8        /* BMP  */
#define rc_gem02a                        9        /* BMP  */
#define rc_gem02b                        10       /* BMP  */
#define rc_gem02c                        11       /* BMP  */
#define rc_gem02d                        12       /* BMP  */
#define rc_gem02e                        13       /* BMP  */
#define rc_gem03r                        14       /* BMP  */
#define rc_gem03g                        15       /* BMP  */
#define rc_gem03b                        16       /* BMP  */
#define rc_gem03v                        17       /* BMP  */
#define rc_gem03y                        18       /* BMP  */
#define rc_gem03b1                       19       /* BMP  */
#define rc_gem03b2                       20       /* BMP  */
#define rc_gem03g1                       21       /* BMP  */
#define rc_gem03r1                       22       /* BMP  */
#define rc_gem05r                        23       /* BMP  */
#define rc_gem05g                        24       /* BMP  */
#define rc_gem05b                        25       /* BMP  */
#define rc_gem05v                        26       /* BMP  */
#define rc_gem05y                        27       /* BMP  */
#define rc_gem06r                        28       /* BMP  */
#define rc_gem06g                        29       /* BMP  */
#define rc_gem06b                        30       /* BMP  */
#define rc_gem06v                        31       /* BMP  */
#define rc_gem06y                        32       /* BMP  */
#define rc_gem07r                        33       /* BMP  */
#define rc_gem07g                        34       /* BMP  */
#define rc_gem07b                        35       /* BMP  */
#define rc_gem07v                        36       /* BMP  */
#define rc_gem07y                        37       /* BMP  */
#define rc_gem08r                        38       /* BMP  */
#define rc_gem08g                        39       /* BMP  */
#define rc_gem08b                        40       /* BMP  */
#define rc_gem08v                        41       /* BMP  */
#define rc_gem08y                        42       /* BMP  */
#define rc_gem09r                        43       /* BMP  */
#define rc_gem09g                        44       /* BMP  */
#define rc_gem09b                        45       /* BMP  */
#define rc_gem09v                        46       /* BMP  */
#define rc_gem09y                        47       /* BMP  */
#define rc_gem10r                        48       /* BMP  */
#define rc_gem10g                        49       /* BMP  */
#define rc_gem10b                        50       /* BMP  */
#define rc_gem10v                        51       /* BMP  */
#define rc_gem10y                        52       /* BMP  */
#define rc_gem11b                        53       /* BMP  */
#define rc_gem11m                        54       /* BMP  */
#define rc_gem28r                        55       /* BMP  */
#define rc_gem28g                        56       /* BMP  */
#define rc_gem28b                        57       /* BMP  */
#define rc_gem28v                        58       /* BMP  */
#define rc_gem28y                        59       /* BMP  */
#define rc_gem13r                        60       /* BMP  */
#define rc_gem13y                        61       /* BMP  */
#define rc_gem14r                        62       /* BMP  */
#define rc_gem14b                        63       /* BMP  */
#define rc_gem15r                        64       /* BMP  */
#define rc_gem15g                        65       /* BMP  */
#define rc_gem15b                        66       /* BMP  */
#define rc_gem15v                        67       /* BMP  */
#define rc_gem15y                        68       /* BMP  */
#define rc_gem16r                        69       /* BMP  */
#define rc_gem16g                        70       /* BMP  */
#define rc_gem16b                        71       /* BMP  */
#define rc_gem16v                        72       /* BMP  */
#define rc_gem16y                        73       /* BMP  */
#define rc_gem16m                        74       /* BMP  */
#define rc_gem17r                        75       /* BMP  */
#define rc_gem18r                        76       /* BMP  */
#define rc_gem18g                        77       /* BMP  */
#define rc_gem18b                        78       /* BMP  */
#define rc_gem18v                        79       /* BMP  */
#define rc_gem18y                        80       /* BMP  */
#define rc_gem19r                        81       /* BMP  */
#define rc_gem19g                        82       /* BMP  */
#define rc_gem19b                        83       /* BMP  */
#define rc_gem19v                        84       /* BMP  */
#define rc_gem19y                        85       /* BMP  */
#define rc_gem20r                        86       /* BMP  */
#define rc_gem20b                        87       /* BMP  */
#define rc_gem20v                        88       /* BMP  */
#define rc_gem21r                        89       /* BMP  */
#define rc_gem21g                        90       /* BMP  */
#define rc_gem21b                        91       /* BMP  */
#define rc_gem21v                        92       /* BMP  */
#define rc_gem21y                        93       /* BMP  */
#define rc_gem22r                        94       /* BMP  */
#define rc_gem22b                        95       /* BMP  */
#define rc_gem22v                        96       /* BMP  */
#define rc_gem23r                        97       /* BMP  */
#define rc_gem23b                        98       /* BMP  */
#define rc_gem23v                        99       /* BMP  */
#define rc_gem24r                        100      /* BMP  */
#define rc_gem24g                        101      /* BMP  */
#define rc_gem24y                        102      /* BMP  */
#define rc_gem25g                        103      /* BMP  */
#define rc_gem25y                        104      /* BMP  */
#define rc_gem26r                        105      /* BMP  */
#define rc_gem26g                        106      /* BMP  */
#define rc_gem26b                        107      /* BMP  */
#define rc_gem26v                        108      /* BMP  */
#define rc_gem26y                        109      /* BMP  */
#define rc_gem27r                        110      /* BMP  */
#define rc_gem27g                        111      /* BMP  */
#define rc_gem27b                        112      /* BMP  */
#define rc_gem27v                        113      /* BMP  */
#define rc_gem27y                        114      /* BMP  */
#define rc_gem29r                        115      /* BMP  */
#define rc_gem29g                        116      /* BMP  */
#define rc_gem29b                        117      /* BMP  */
#define rc_gem29v                        118      /* BMP  */
#define rc_gem29y                        119      /* BMP  */
#define rc_gem30r                        120      /* BMP  */
#define rc_gem30g                        121      /* BMP  */
#define rc_gem30b                        122      /* BMP  */
#define rc_gem30v                        123      /* BMP  */
#define rc_gem30y                        124      /* BMP  */
#define rc_gem33a                        125      /* BMP  */
#define rc_gem33b                        126      /* BMP  */
#define rc_gem33c                        127      /* BMP  */
#define rc_gem33d                        128      /* BMP  */
#define rc_gem33e                        129      /* BMP  */
#define rc_gem33f                        130      /* BMP  */
#define rc_gem35a                        131      /* BMP  */
#define rc_gem35b                        132      /* BMP  */
#define rc_gem35c                        133      /* BMP  */
#define rc_gem35d                        134      /* BMP  */
#define rc_gem35e                        135      /* BMP  */
#define rc_gem35f                        136      /* BMP  */
#define rc_gem35g                        137      /* BMP  */
#define rc_gem35h                        138      /* BMP  */
#define rc_gem35i                        139      /* BMP  */
#define rc_gem35j                        140      /* BMP  */
#define rc_gem35k                        141      /* BMP  */
#define rc_gem36a                        142      /* BMP  */
#define rc_gem36b                        143      /* BMP  */
#define rc_gem36c                        144      /* BMP  */
#define rc_gem36d                        145      /* BMP  */
#define rc_gem36e                        146      /* BMP  */
#define rc_gem36f                        147      /* BMP  */
#define rc_gem36g                        148      /* BMP  */
#define rc_gem36h                        149      /* BMP  */
#define rc_gem36i                        150      /* BMP  */
#define rc_gem36j                        151      /* BMP  */
#define rc_gem37a                        152      /* BMP  */
#define rc_gem37b                        153      /* BMP  */
#define rc_gem37c                        154      /* BMP  */
#define rc_gem37d                        155      /* BMP  */
#define rc_gem37e                        156      /* BMP  */
#define rc_gem37f                        157      /* BMP  */
#define rc_gem37g                        158      /* BMP  */
#define rc_gem37h                        159      /* BMP  */
#define rc_gem37i                        160      /* BMP  */
#define rc_gem37j                        161      /* BMP  */
#define rc_gem37k                        162      /* BMP  */
#define rc_gem38a                        163      /* BMP  */
#define rc_gem38b                        164      /* BMP  */
#define rc_gem38c                        165      /* BMP  */
#define rc_gem38d                        166      /* BMP  */
#define rc_gem38e                        167      /* BMP  */
#define rc_gem38f                        168      /* BMP  */
#define rc_gem39a                        169      /* BMP  */
#define rc_gem39b                        170      /* BMP  */
#define rc_gem39c                        171      /* BMP  */
#define rc_gem39d                        172      /* BMP  */
#define rc_gem39e                        173      /* BMP  */
#define rc_gem39f                        174      /* BMP  */
#define rc_gem40a                        175      /* BMP  */
#define rc_gem40b                        176      /* BMP  */
#define rc_gem40c                        177      /* BMP  */
#define rc_gem40d                        178      /* BMP  */
#define rc_gem40e                        179      /* BMP  */
#define rc_gem40f                        180      /* BMP  */
#define rc_gem41a                        181      /* BMP  */
#define rc_gem41b                        182      /* BMP  */
#define rc_gem41c                        183      /* BMP  */
#define rc_gem41d                        184      /* BMP  */
#define rc_gem41e                        185      /* BMP  */
#define rc_gem41f                        186      /* BMP  */
#define rc_gem42a                        187      /* BMP  */
#define rc_gem42b                        188      /* BMP  */
#define rc_gem42c                        189      /* BMP  */
#define rc_gem42d                        190      /* BMP  */
#define rc_gem42e                        191      /* BMP  */
#define rc_gem42f                        192      /* BMP  */
#define rc_gem43a                        193      /* BMP  */
#define rc_gem43b                        194      /* BMP  */
#define rc_gem43c                        195      /* BMP  */
#define rc_gem43d                        196      /* BMP  */
#define rc_gem43e                        197      /* BMP  */
#define rc_gem43f                        198      /* BMP  */
#define rc_the_last                      199      /* BMP  */
#define rc_----------(bg's)              200      /*      */
#define rc_dlg_entername                 201      /* JPEG */
#define rc_bg_menu                       202      /* JPEG */
#define rc_bg_options                    203      /* JPEG */
#define rc_bg_scores                     204      /* JPEG */
#define rc_bg_copy                       205      /* JPEG */
#define rc_bg00                          206      /* JPEG */
#define rc_bg01                          207      /* JPEG */
#define rc_bg02                          208      /* JPEG */
#define rc_bg03                          209      /* JPEG */
#define rc_bg04                          210      /* JPEG */
#define rc_bg05                          211      /* JPEG */
#define rc_bg08                          212      /* JPEG */
#define rc_bg10                          213      /* JPEG */
#define rc_bg12                          214      /* JPEG */
#define rc_bg13                          215      /* JPEG */
#define rc_bg14                          216      /* JPEG */
#define rc_bg16                          217      /* JPEG */
#define rc_bg17                          218      /* JPEG */
#define rc_bg18                          219      /* JPEG */
#define rc_bg21                          220      /* JPEG */
#define rc_bg22                          221      /* JPEG */
#define rc_bg24                          222      /* JPEG */
#define rc_bg25                          223      /* JPEG */
#define rc_-------(buttons)              224      /*      */
#define rc_btn_ok                        225      /* JPEG */
#define rc_btn_ok2                       226      /* JPEG */
#define rc_btn_play                      227      /* JPEG */
#define rc_btn_options                   228      /* JPEG */
#define rc_btn_scores                    229      /* JPEG */
#define rc_btn_exit                      230      /* JPEG */
#define rc_btn_fullscreen                231      /* JPEG */
#define rc_btn_windowed                  232      /* JPEG */
#define rc_btn_muzvol1                   233      /* JPEG */
#define rc_btn_muzvol2                   234      /* JPEG */
#define rc_btn_muzvol3                   235      /* JPEG */
#define rc_btn_muzvol4                   236      /* JPEG */
#define rc_btn_muzvol5                   237      /* JPEG */
#define rc_btn_sndvol1                   238      /* JPEG */
#define rc_btn_sndvol2                   239      /* JPEG */
#define rc_btn_sndvol3                   240      /* JPEG */
#define rc_btn_sndvol4                   241      /* JPEG */
#define rc_btn_sndvol5                   242      /* JPEG */
#define rc_btn_p_exit                    243      /* JPEG */
#define rc_btn_p_restart                 244      /* JPEG */
#define rc_btn_p_continue                245      /* JPEG */
#define rc_---------(utils)              246      /*      */
#define rc_palette                       247      /* PAL  */
#define rc_font                          248      /* FONT */
#define rc_font_empty                    249      /* FONT */
#define rc_mouse                         250      /* BMP  */
#define rc_nomouse                       251      /* BMP  */
#define rc_selected                      252      /* BMP  */
#define rc_selfirst                      253      /* BMP  */
#define rc_pause                         254      /* BMP  */
#define rc_pause_menu                    255      /* BMP  */
#define rc_stats                         256      /* BMP  */
#define rc_---------(bonus)              257      /*      */
#define rc_b_ball_spd_up                 258      /* BMP  */
#define rc_b_ball_spd_dn                 259      /* BMP  */
#define rc_b_bite_spd_up                 260      /* BMP  */
#define rc_b_bite_spd_dn                 261      /* BMP  */
#define rc_b_rev_con                     262      /* BMP  */
#define rc_b_ball_joint                  263      /* BMP  */
#define rc_b_rocket                      264      /* BMP  */
#define rc_b_life                        265      /* BMP  */
#define rc_b_money                       266      /* BMP  */
#define rc_msg_ball_spd_up               267      /* BMP  */
#define rc_msg_ball_spd_dn               268      /* BMP  */
#define rc_msg_bite_spd_up               269      /* BMP  */
#define rc_msg_bite_spd_dn               270      /* BMP  */
#define rc_msg_rev_con                   271      /* BMP  */
#define rc_msg_ball_joint                272      /* BMP  */
#define rc_msg_rocket                    273      /* BMP  */
#define rc_msg_life                      274      /* BMP  */
#define rc_msg_gogogo                    275      /* BMP  */
#define rc_msg_gameover                  276      /* BMP  */
#define rc_msg_money                     277      /* BMP  */
#define rc_-----(particles)              278      /*      */
#define rc_p01                           279      /* BMP  */
#define rc_p_std_r                       280      /* BMP  */
#define rc_p_std_g                       281      /* BMP  */
#define rc_p_std_b                       282      /* BMP  */
#define rc_p_std_y                       283      /* BMP  */
#define rc_p_sml_r                       284      /* BMP  */
#define rc_p_sml_g                       285      /* BMP  */
#define rc_p_sml_b                       286      /* BMP  */
#define rc_p_sml_y                       287      /* BMP  */
#define rc_p_mid_r                       288      /* BMP  */
#define rc_p_mid_g                       289      /* BMP  */
#define rc_p_mid_b                       290      /* BMP  */
#define rc_p_mid_v                       291      /* BMP  */
#define rc_p_mid_y                       292      /* BMP  */
#define rc_p_big_r                       293      /* BMP  */
#define rc_p_big_g                       294      /* BMP  */
#define rc_p_big_b                       295      /* BMP  */
#define rc_p_big_y                       296      /* BMP  */
#define rc_-----------(sfx)              297      /*      */
#define rc_glass_1                       298      /* SAMP */
#define rc_glass_3                       299      /* SAMP */
#define rc_glass_4                       300      /* SAMP */
#define rc_glass_5                       301      /* SAMP */
#define rc_glass_7                       302      /* SAMP */
#define rc_seaside                       303      /* SAMP */
#define rc_steel_1                       304      /* SAMP */
#define rc_tymp_1                        305      /* SAMP */
#define rc_tymp_10                       306      /* SAMP */
#define rc_wood_10                       307      /* SAMP */
#define rc_wood_20                       308      /* SAMP */
#define rc_wood_25                       309      /* SAMP */
#define rc_wood_30                       310      /* SAMP */
#define rc_tr                            311      /* SAMP */
#define rc_rocket                        312      /* SAMP */
#define rc_gameover                      313      /* SAMP */
#define rc_drum                          314      /* SAMP */
#define rc_COUNT                         315

